enum class NombreEvento(val nombreEvento: String) {
    CAMBIO_CLIMATICO("Foro sobre Cambio Climático"),
    ENERGIA_RENOVABLE("Cumbre de Energías Renovables"),
    RECICLAJE_INNOVADOR("Encuentro de Reciclaje Innovador"),
    CIUDAD_VERDE("Festival de Ciudades Verdes"),
    ECO_INNOVACION("Jornada de Eco Innovación"),
    MOVILIDAD_SOSTENIBLE("Congreso de Movilidad Sostenible"),
    AGRICULTURA_ORGANICA("Feria de Agricultura Orgánica"),
    BOSQUES_URBANOS("Seminario de Bosques Urbanos"),
    ECO_TECNOLOGIA("Exposición de Eco Tecnología"),
    AHORRO_ENERGETICO("Foro de Ahorro Energético"),
    CALIDAD_DEL_AIRE("Cumbre de Calidad del Aire"),
    GESTION_AGUA("Jornadas de Gestión del Agua"),
    RSC_EMPRESARIAL("Conferencia de RSC Empresarial"),
    COMPROMISO_VERDE("Encuentro de Compromiso Verde"),
    ECO_CIUDADANOS("Taller de Eco Ciudadanía"),
    SOSTENIBILIDAD_URBANA("Cumbre de Sostenibilidad Urbana"),
    ECONOMIA_CIRCULAR("Foro de Economía Circular"),
    IMPACTO_AMBIENTAL("Simposio sobre Impacto Ambiental"),
    INNOVACION_SOSTENIBLE("Feria de Innovación Sostenible"),
    ECO_EMPRENDEDORES("Encuentro de Eco Emprendedores"),
    TECNOLOGIA_VERDE("Congreso de Tecnología Verde"),
    CIENCIA_SOSTENIBLE("Jornada de Ciencia Sostenible"),
    EDUCACION_AMBIENTAL("Taller de Educación Ambiental"),
    REDUCCION_RESIDUOS("Foro de Reducción de Residuos"),
    MOVILIDAD_ELECTRICA("Cumbre de Movilidad Eléctrica"),
    CALOR_SUSTENTABLE("Seminario de Energía Sustentable"),
    RECURSOS_NATURALES("Encuentro sobre Recursos Naturales"),
    CIUDAD_EFICIENTE("Foro de Ciudades Eficientes"),
    ECO_PRODUCTOS("Feria de Eco Productos"),
    BIODIVERSIDAD("Cumbre de Biodiversidad"),
    ECO_TURISMO("Encuentro de Eco Turismo"),
    REDUCCION_EMISIONES("Simposio de Reducción de Emisiones"),
    ALIMENTACION_SOSTENIBLE("Foro de Alimentación Sostenible"),
    REUTILIZACION("Taller de Reutilización"),
    SISTEMAS_VERDES("Congreso de Sistemas Verdes"),
    RESIDUOS_CERO("Jornada de Residuos Cero"),
    CAMBIO_VERDE("Cumbre del Cambio Verde"),
    ENERGIA_SOLAR("Foro de Energía Solar"),
    ENERGIA_EOLICA("Seminario de Energía Eólica"),
    ECO_INVERSIONES("Encuentro de Eco Inversiones"),
    RECUPERACION_AMBIENTAL("Simposio de Recuperación Ambiental"),
    SOSTENIBILIDAD_FINANCIERA("Taller de Sostenibilidad Financiera"),
    ECO_DISENO("Feria de Eco Diseño"),
    BIOMASA("Foro de Biomasa"),
    TECNOLOGIA_LIMPIA("Congreso de Tecnología Limpia"),
    CIUDAD_CIRCULAR("Jornada de Ciudades Circulares"),
    ECO_GESTION("Encuentro de Eco Gestión"),
    CLIMA_Y_TRANSICION("Simposio Clima y Transición"),
    SOSTENIBILIDAD_PRODUCTIVA("Foro de Sostenibilidad Productiva"),
    FUTURO_SUSTENTABLE("Cumbre del Futuro Sostenible ");
    companion object{
        fun devolverNombreEventoAleatorio():String{
            return values().random().nombreEvento
        }
    }
}
