DROP TABLE EVENTO_ORGANIZADOR;
DROP TABLE USUARIO_ASISTE;
DROP TABLE USUARIO_INSCRITO;
DROP TABLE ORGANIZADOR;
DROP TABLE ORGANIZADORES;
DROP TABLE USUARIO;
DROP TABLE CATEGORIA_EVENTO;
DROP TABLE EVENTO;
DROP TABLE CATEGORIA;
-----------
CREATE TABLE CATEGORIA(
NOMBRE VARCHAR2(20) PRIMARY KEY
);

CREATE TABLE EVENTO (
ID_EVENTO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
FECHA_EVENTO DATE NOT NULL,
DURACION NUMBER(5,2) NOT NULL,
UBICACION VARCHAR2(200) NOT NULL,
CATEGORIA VARCHAR2(20),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA)
REFERENCES CATEGORIA(NOMBRE)
);

CREATE TABLE CATEGORIA_EVENTO(
ID_EVENTO NUMBER(10) GENERATED ALWAYS AS IDENTITY,
CATEGORIA VARCHAR2(20),
CONSTRAINT FK_EVENTO FOREIGN KEY (ID_EVENTO)
REFERENCES EVENTO (ID_EVENTO),
CONSTRAINT FK_CATEGORIA_EVENTO FOREIGN KEY (CATEGORIA)
REFERENCES CATEGORIA (NOMBRE),
CONSTRAINT PK_CATEGORIA_EVENTO PRIMARY KEY(ID_EVENTO,CATEGORIA)
);

CREATE TABLE USUARIO (
ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2(20) NOT NULL,
APELLIDO1 VARCHAR2(20) NOT NULL,
APELLIDO2 VARCHAR2(20),
EMAIL VARCHAR2(30) NOT NULL,
CONTRASEÑA VARCHAR2(30) NOT NULL

);

CREATE TABLE ORGANIZADOR (
ID_ORGANIZADOR NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
TELEFONO NUMBER(9) NOT NULL
);

CREATE TABLE USUARIO_INSCRITO (
ID_INSCRIPCION NUMBER(10) GENERATED ALWAYS AS IDENTITY,
ID_USUARIO NUMBER(10),
ID_EVENTO NUMBER(10),
CONSTRAINT FK_USUARIO_INSCRITO FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO(ID_USUARIO),
CONSTRAINT FK_EVENTO_INSCRITO FOREIGN KEY (ID_EVENTO) 
REFERENCES EVENTO(ID_EVENTO),
CONSTRAINT PK_USUARIO_EVENTO PRIMARY KEY (ID_INSCRIPCION,ID_USUARIO, ID_EVENTO)
);

CREATE TABLE USUARIO_ASISTE(
ID_USUARIO NUMBER(10),
ID_EVENTO NUMBER(10),
ASISTIO CHAR(1) CHECK (ASISTIO IN ('S','N'))NOT NULL,
CONSTRAINT FK_USUARIO_ASISTE FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO(ID_USUARIO),
CONSTRAINT FK_EVENTO_ASISTE FOREIGN KEY (ID_EVENTO) 
REFERENCES EVENTO(ID_EVENTO),
CONSTRAINT PK_ASISTENCIA PRIMARY KEY (ID_USUARIO,ID_EVENTO)
);

CREATE TABLE EVENTO_ORGANIZADOR (
ID_ORGANIZADOR NUMBER(10),
ID_EVENTO NUMBER(10),
CONSTRAINT FK_ORGANIZADOR_EVENTO FOREIGN KEY (ID_ORGANIZADOR)
REFERENCES ORGANIZADOR (ID_ORGANIZADOR),
CONSTRAINT FK_EVENTO_ORGANIZADOR FOREIGN KEY (ID_EVENTO)
REFERENCES EVENTO (ID_EVENTO)
);


